POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkZyYW5raXRvIiwiaWQiOiI2Nzk2YWRhOGY1Yjc3ZmRmNDdhYzdmNjgiLCJpYXQiOjE3Mzc5Mjg2Mzh9.eRe5qJVA2Qag_9peeT-JcdNsIZ9CkUAg4ENGdoHYDXk

{
  "content": "rest client is fkin cool",
  "important": false
}